# SPDX-License-Identifier: MPL-2.0

cargo-features = ["profile-rustflags"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
dirs = "4.0"
error-stack = "0.2"
tokio = { version = "1.24", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
