# SPDX-License-Identifier: MPL-2.0

[package]
name = "norepi-site-util"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
