# SPDX-License-Identifier: MPL-2.0

[package]
name = "norepi-site-db-types"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
